version: "3" # composeファイルのバージョン
services: 
    app: # サービス名
        build: . # ①ビルドに使うDockerfileの場所
        tty: true # ②コンテナの永続化
        ports: # ホストOSのポートとコンテナのポートをつなげる 
            - "8080:8080"
        volumes:
            - ./app:/go/src/app # ③マウントディレクトリ