apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: cloudwatch-test
  labels:
    app: cloudwatch-test
spec:
  selector:
    app: cloudwatch-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-deployment
  namespace: cloudwatch-test
  labels:
    app: cloudwatch-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloudwatch-test
  template:
    metadata:
      labels:
        app: cloudwatch-test
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: nginx
          image: public.ecr.aws/z9d2n7e1/nginx:1.19.5
          ports:
            - containerPort: 80
